// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAorwlEjLdeu9jMi_OqJjmyHIXpssdOC_s',
    appId: '1:963436293913:web:daa4b1365bbb88e5da9f88',
    messagingSenderId: '963436293913',
    projectId: 'exam-56214',
    authDomain: 'exam-56214.firebaseapp.com',
    storageBucket: 'exam-56214.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB90q05YRWGnPKh4wDxxfW_izxg_MmBfTI',
    appId: '1:963436293913:android:4dd81ba304a12459da9f88',
    messagingSenderId: '963436293913',
    projectId: 'exam-56214',
    storageBucket: 'exam-56214.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr8kg3CXU83ctCvbzpoWksgEt-ei_nDjM',
    appId: '1:963436293913:ios:7217a4df38637ffcda9f88',
    messagingSenderId: '963436293913',
    projectId: 'exam-56214',
    storageBucket: 'exam-56214.appspot.com',
    iosBundleId: 'com.example.examAdvFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr8kg3CXU83ctCvbzpoWksgEt-ei_nDjM',
    appId: '1:963436293913:ios:7217a4df38637ffcda9f88',
    messagingSenderId: '963436293913',
    projectId: 'exam-56214',
    storageBucket: 'exam-56214.appspot.com',
    iosBundleId: 'com.example.examAdvFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAorwlEjLdeu9jMi_OqJjmyHIXpssdOC_s',
    appId: '1:963436293913:web:c6c001a04133dc16da9f88',
    messagingSenderId: '963436293913',
    projectId: 'exam-56214',
    authDomain: 'exam-56214.firebaseapp.com',
    storageBucket: 'exam-56214.appspot.com',
  );
}
